version: "3.6"

services:
    sistema.revenda:
        image: ${DOCKER_REGISTRY-}revendaweb
        build:
            context: .
            dockerfile: src/Senior.Revenda.Mvc/Dockerfile
        ports:
            - 4200:4200
            
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        deploy:
            resources:
                limits:
                    memory: 2048MB
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "seniorRevend@"
            
    rabbitmq:
        image: rabbitmq:3-management
        container_name: revenda-rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin